local M = {}
M.SCREEN_WIDTH = 1280
M.SCREEN_HEIGHT = 720
M.TILE_WIDTH = 160
M.TILE_HEIGHT = 80
M.BOARD_WIDTH = 8
M.BOARD_HEIGHT = 8
M.STATISTICS_FONT_SIZE = 24
M.LINE_HEIGHT = 36
M.PAWN_COUNT = 8
M.MESSAGE_FONT_SIZE = 12
M.MESSAGE_LINE_HEIGHT = 18
M.LOTION_X = M.SCREEN_WIDTH - 96
M.LOTION_Y = M.SCREEN_HEIGHT - 96
return M